"""db change

Revision ID: 3a035e6d3e75
Revises: a4fafc68729f
Create Date: 2020-02-17 13:48:42.134755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a035e6d3e75'
down_revision = 'a4fafc68729f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Indicators', sa.Column('description', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Indicators', 'description')
    # ### end Alembic commands ###
