"""db change

Revision ID: 49fe5c552782
Revises: 3a035e6d3e75
Create Date: 2020-02-17 13:55:57.030245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fe5c552782'
down_revision = '3a035e6d3e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Reasons_description_key', 'Reasons', type_='unique')
    op.drop_column('Reasons', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reasons', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('Reasons_description_key', 'Reasons', ['description'])
    # ### end Alembic commands ###
