"""db corrections

Revision ID: c8f9da463fd4
Revises: ad3c9211c3a9
Create Date: 2020-02-17 10:54:38.318149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f9da463fd4'
down_revision = 'ad3c9211c3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'Diagnoses', type_='foreignkey')
    #op.create_foreign_key(None, 'Diagnoses', 'DiagnosesItems', ['diagnose'], ['id'])
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Diagnoses', type_='foreignkey')
    op.create_foreign_key(None, 'Diagnoses', 'Diagnoses', ['diagnose'], ['id'])
    # ### end Alembic commands ###
